name: Python
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref || github.ref }}
env:
  LINEAPY_DO_NOT_TRACK: true
  PYTHONUSERBASE: /opt/hostedtoolcache/linea
jobs:
  pre-commit:
    name: ${{ matrix.id }}
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: ${{ matrix.id }} --all-files
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740230992.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740230992.json
    strategy:
      matrix:
        id:
          - black
          - flake8
          - isort
          - mypy
        python-version:
          - '3.9'
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - id: pipcache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt')
            }}
          path: '/home/runner/.cache/pip

            /opt/hostedtoolcache/linea/lib/python${{ matrix.python-version }}/site-packages

            '
          restore-keys: '${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles(''**/requirements.txt'')
            }}

            ${{ runner.os }}-pip-${{ matrix.python-version }}

            ${{ runner.os }}-pip

            '
      - if: steps.pipcache.outputs.cache-hit != 'true'
        name: Install pip dependencies
        run: 'pip install wheel && python -m pip install --user -r requirements.txt

          '
      - id: measurement-5
        name: Record Measurement After Install pip dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install pip dependencies
          task: get-measurement
      - name: Install linea
        run: 'python setup.py install && rm -rf build

          '
      - id: measurement-7
        name: Record Measurement After Install linea
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install linea
          task: get-measurement
      - name: Test with pytest
        run: 'python -m pytest -v

          '
      - id: measurement-9
        name: Record Measurement After Test with pytest
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Test with pytest
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740230992.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740230992.json
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
