name: Sync Demos and docs
on:
  push:
    branches:
      - main

jobs:
  sync-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy demo & tutorial notebooks to top level .colab folder
        run: rm -rf .colab/ && mkdir -p .colab/ && cp -R examples/use_cases/* .colab/
          && cp -R examples/tutorials/* .colab/
      - id: measurement-3
        name: Record Measurement After Copy demo & tutorial notebooks to top level
          .colab folder
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Copy demo & tutorial notebooks to top level .colab folder
          task: get-measurement
      - name: Copy tutorial notebooks to docs
        run: 'cp -R examples/tutorials/* docs/mkdocs/tutorials/

          find docs/mkdocs/tutorials/* -type f -name "*.ipynb" -exec sed -i ''s/(\#.*)/\L&/g''
          {} \;

          '
      - id: measurement-5
        name: Record Measurement After Copy tutorial notebooks to docs
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Copy tutorial notebooks to docs
          task: get-measurement
      - name: Regex out the NBVAL_SKIP and NBVAL_IGNORE_OUTPUT comments
        run: "cd .colab/ \nfind ./ -type f -name \"*.ipynb\" -exec sed -i 's/\\#[\\\
          \ ]*NBVAL_SKIP//g' {} \\;\nfind ./ -type f -name \"*.ipynb\" -exec sed -i\
          \ 's/\\#[\\ ]*NBVAL_IGNORE_OUTPUT//g' {} \\;\n"
      - id: measurement-7
        name: Record Measurement After Regex out the NBVAL_SKIP and NBVAL_IGNORE_OUTPUT
          comments
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Regex out the NBVAL_SKIP and NBVAL_IGNORE_OUTPUT comments
          task: get-measurement
      - name: Commit files
        run: 'git config --local user.email "infra@linea.ai"

          git config --local user.name "Humble bot servant"

          git add docs/mkdocs/tutorials/*

          git add .colab/

          (git diff --quiet && git diff --staged --quiet) || git commit -m "Refresh
          demos folder and update docs"

          '
      - id: measurement-9
        name: Record Measurement After Commit files
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Commit files
          task: get-measurement
      - name: push synced changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740230992.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740230992.json
